### ISSUE TITLE
vscode-oniguruma

### ISSUE THREAD

**Issue by caenguidanos** [shikijs/shiki#360]
Seems that vscode-oniguruma dependency is failing randomly in my setup.

Logs:

```bash
# arrow function possible to detect only with => on same line
(
  (<\s*([_$[:alpha:]]|(\{([^\{\}]|(\{([^\{\}]|\{[^\{\}]*\})*\}))*\})|(\(([^\(\)]|(\(([^\(\)]|\([^\(\)]*\))*\)))*\))|(\[([^\[\]]|(\[([^\[\]]|\[[^\[\]]*\])*\]))*\]))([^=<>]|=[^<]|\<\s*([_$[:alpha:]]|(\{([^\{\}]|(\{([^\{\}]|\{[^\{\}]*\})*\}))*\})|(\(([^\(\)]|(\(([^\(\)]|\([^\(\)]*\))*\)))*\))|(\[([^\[\]]|(\[([^\[\]]|\[[^\[\]]*\])*\]))*\]))([^=<>]|=[^<]|\<\s*([_$[:alpha:]]|(\{([^\{\}]|(\{([^\{\}]|\{[^\{\}]*\})*\}))*\})|(\(([^\(\)]|(\(([^\(\)]|\([^\(\)]*\))*\)))*\))|(\[([^\[\]]|(\[([^\[\]]|\[[^\[\]]*\])*\]))*\]))([^=<>]|=[^<])*\>)*\>)*>\s*)?                                                                                 # typeparameters
  \(\s*(\/\*([^\*]|(\*[^\/]))*\*\/\s*)*(([_$[:alpha:]]|(\{([^\{\}]|(\{([^\{\}]|\{[^\{\}]*\})*\}))*\})|(\[([^\[\]]|(\[([^\[\]]|\[[^\[\]]*\])*\]))*\])|(\.\.\.\s*[_$[:alpha:]]))([^()\'\"\`]|(\(([^\(\)]|(\(([^\(\)]|\([^\(\)]*\))*\)))*\))|(\'([^\'\\]|\\.)*\')|(\"([^\"\\]|\\.)*\")|(\`([^\`\\]|\\.)*\`))*)?\)   # parameters
  (\s*:\s*([^<>\(\)\{\}]|\<([^<>]|\<([^<>]|\<[^<>]+\>)+\>)+\>|\([^\(\)]+\)|\{[^\{\}]+\})+)?                                                                        # return type
  \s*=>                                                                                               # arrow operator
)
  ))
))

at /Users/x/github.com/x/blog/www/node_modules/.pnpm/vscode-oniguruma@1.6.2/node_modules/vscode-oniguruma/release/main.js:1:3107
    at new u (/Users/x/github.com/x/blog/www/node_modules/.pnpm/vscode-oniguruma@1.6.2/node_modules/vscode-oniguruma/release/main.js:1:3156)
    at n.createOnigScanner (/Users/x/github.com/x/blog/www/node_modules/.pnpm/vscode-oniguruma@1.6.2/node_modules/vscode-oniguruma/release/main.js:1:4986)
    at Object.createOnigScanner (/Users/x/github.com/x/blog/www/node_modules/.pnpm/shiki@0.11.1/node_modules/shiki/dist/index.js:1687:34)
    at e.createOnigScanner (/Users/x/github.com/x/blog/www/node_modules/.pnpm/vscode-textmate@6.0.0/node_modules/vscode-textmate/release/main.js:1:6723)
    at new e (/Users/x/github.com/x/blog/www/node_modules/.pnpm/vscode-textmate@6.0.0/node_modules/vscode-textmate/release/main.js:1:39681)
    at e._resolveAnchors (/Users/x/github.com/x/blog/www/node_modules/.pnpm/vscode-textmate@6.0.0/node_modules/vscode-textmate/release/main.js:1:44610)
    at e.compileAG (/Users/x/github.com/x/blog/www/node_modules/.pnpm/vscode-textmate@6.0.0/node_modules/vscode-textmate/release/main.js:1:44214)
    at t.compileAG (/Users/x/github.com/x/blog/www/node_modules/.pnpm/vscode-textmate@6.0.0/node_modules/vscode-textmate/release/main.js:1:46291)
    at A (/Users/x/github.com/x/blog/www/node_modules/.pnpm/vscode-textmate@6.0.0/node_modules/vscode-textmate/release/main.js:1:11076)
```

My setup:
- Macbook air m1
- nodejs v18.6.0

Implementation: [here](https://github.com/caenguidanos/blog/blob/main/www/src/domain/shared/util/render-code-block.ts)

**Comment by octref** [comment]
Can you please provide the minimal code with which I can see the problem? Thanks.

**Comment by caenguidanos** [comment]
[here](https://github.com/caenguidanos/blog/blob/main/www/src/domain/shared/util/render-code-block.ts)

**Comment by octref** [comment]
reduce it to something like this please

<img width="759" alt="image" src="https://user-images.githubusercontent.com/4033249/191574085-7fe703a5-e698-40ca-80a9-7122bd28f755.png">

**Comment by muenzpraeger** [comment]
@caenguidanos Is this still an issue [with 0.12.0](https://github.com/shikijs/shiki/releases/tag/v0.12.0)?

**Comment by caenguidanos** [comment]
I don't know because i removed the use case. If i have more evidences i'll put here.

**Comment by muenzpraeger** [comment]
@caenguidanos Feel free to re-open once you have more evidence, closing for now.
