### ISSUE TITLE
various files are not found when used in Sveltekit

### ISSUE THREAD

**Issue by marcopolo1124** [shikijs/shiki#556]
I am trying to do some syntax highlighting on markdown blog site. I used marked-highlight in conjunction with shiki to achieve this in sveltekit.

```ts
import {Marked} from 'marked'
import {getHighlighter} from 'shiki'

export const markedShiki = new Marked(
	markedHighlight({
        async: true,
		async highlight(code, lang) {
			const highlighter = await getHighlighter({
				theme: 'nord'
			});
			const html = highlighter.codeToHtml(code, { lang });
			return html;
		}
	})
);

//+page.ts

async function load({params}){
  ...
  return await marked.parse(txt)
}
```

This sometimes will load the code perfectly for 1 second before telling me that it has failed. With the error looking like this:

```
SvelteKitError: Not found: /themes/nord.json
    at resolve (C:\Users\leung\OneDrive\Desktop\Programming\mdsvex\markdown-blog-mdsvex-ts\node_modules\@sveltejs\kit\src\runtime\server\respond.js:495:13)
    at resolve (C:\Users\leung\OneDrive\Desktop\Programming\mdsvex\markdown-blog-mdsvex-ts\node_modules\@sveltejs\kit\src\runtime\server\respond.js:295:5)
    at #options.hooks.handle (C:\Users\leung\OneDrive\Desktop\Programming\mdsvex\markdown-blog-mdsvex-ts\node_modules\@sveltejs\kit\src\runtime\server\index.js:63:56)
    at Module.respond (C:\Users\leung\OneDrive\Desktop\Programming\mdsvex\markdown-blog-mdsvex-ts\node_modules\@sveltejs\kit\src\runtime\server\respond.js:292:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /dist/onig.wasm
    at resolve (C:\Users\leung\OneDrive\Desktop\Programming\mdsvex\markdown-blog-mdsvex-ts\node_modules\@sveltejs\kit\src\runtime\server\respond.js:495:13)
    at resolve (C:\Users\leung\OneDrive\Desktop\Programming\mdsvex\markdown-blog-mdsvex-ts\node_modules\@sveltejs\kit\src\runtime\server\respond.js:295:5)
    at #options.hooks.handle (C:\Users\leung\OneDrive\Desktop\Programming\mdsvex\markdown-blog-mdsvex-ts\node_modules\@sveltejs\kit\src\runtime\server\index.js:63:56)
    at Module.respond (C:\Users\leung\OneDrive\Desktop\Programming\mdsvex\markdown-blog-mdsvex-ts\node_modules\@sveltejs\kit\src\runtime\server\respond.js:292:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /themes/nord.json
    at resolve (C:\Users\leung\OneDrive\Desktop\Programming\mdsvex\markdown-blog-mdsvex-ts\node_modules\@sveltejs\kit\src\runtime\server\respond.js:495:13)
    at resolve (C:\Users\leung\OneDrive\Desktop\Programming\mdsvex\markdown-blog-mdsvex-ts\node_modules\@sveltejs\kit\src\runruntime\server\respond.js:295:5)
    at #options.hooks.handle (C:\Users\leung\OneDrive\Desktop\Programming\mdsvex\markdown-blog-mdsvex-ts\node_modules\@sveltejs\kit\src\runtime\server\index.js:63:56)
    at Module.respond (C:\Users\leung\OneDrive\Desktop\Programming\mdsvex\markdown-blog-mdsvex-ts\node_modules\@sveltejs\kit\src\runtime\server\respond.js:292:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}

```

The list is a lot longer but it seems to not be able to find the files. I made sure that they are definitely in node modules.

**Comment by marcopolo1124** [comment]
![image](https://github.com/shikijs/shiki/assets/85742840/b8de1cb7-1ce8-4b93-a81e-7a17eb5302f8)
it seems to be looking at my api routes for some reasons.
