### ISSUE TITLE
Support for non-default shikijs themes is broken

### ISSUE THREAD

**Issue by gka** [shikijs/shiki#586]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

I think the [update to Shikijs 1](https://github.com/SveltePress/sveltepress/pull/222/files#diff-19c14d74aca012d2c6dafa0af9c5e4fc829ef985b4be14dc8b01526565d436feR20-R24) broke support for the non-default highlighter themes.

E.g. using `github-light` instead of `vitesse-light` will result in this error message:

```
Internal server error: Theme `github-light` not found, you may need to load it first
  Plugin: @sveltepress/vite
  File: /../sveltepress-project/src/routes/hello/+page.md
      at getTheme (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:5292:19)
      at Object.setTheme (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:5296:23)
      at codeToTokensBase (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:516:42)
      at codeToTokens (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:759:18)
      at codeToHast (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:991:53)
      at codeToHtml (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:4552:25)
      at Object.codeToHtml (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:5345:40)
      at Object.highlighter [as light] (file:///../sveltepress-project/node_modules/.pnpm/@sveltepress+theme-default@1.22.4_@algolia+client-search@4.22.1_@sveltejs+kit@2.5.0_@sveltejs_gzh4k2qsptoujdmnwzm3iacupy/node_modules/@sveltepress/theme-default/dist/markdown/highlighter.js:60:83)
      at file:///../sveltepress-project/node_modules/.pnpm/@sveltepress+theme-default@1.22.4_@algolia+client-search@4.22.1_@sveltejs+kit@2.5.0_@sveltejs_gzh4k2qsptoujdmnwzm3iacupy/node_modules/@sveltepress/theme-default/dist/markdown/highlighter.js:126:107
      at step (file:///../sveltepress-project/node_modules/.pnpm/@sveltepress+theme-default@1.22.4_@algolia+client-search@4.22.1_@sveltejs+kit@2.5.0_@sveltejs_gzh4k2qsptoujdmnwzm3iacupy/node_modules/@sveltepress/theme-default/dist/markdown/highlighter.js:32:23)
ShikiError: Theme `github-light` not found, you may need to load it first
    at getTheme (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:5292:19)
    at Object.setTheme (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:5296:23)
    at codeToTokensBase (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:516:42)
    at codeToTokens (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:759:18)
    at codeToHast (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:991:53)
    at codeToHtml (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:4552:25)
    at Object.codeToHtml (file:///../sveltepress-project/node_modules/.pnpm/@shikijs+core@1.1.1/node_modules/@shikijs/core/dist/index.mjs:5345:40)
    at Object.highlighter [as light] (file:///../sveltepress-project/node_modules/.pnpm/@sveltepress+theme-default@1.22.4_@algolia+client-search@4.22.1_@sveltejs+kit@2.5.0_@sveltejs_gzh4k2qsptoujdmnwzm3iacupy/node_modules/@sveltepress/theme-default/dist/markdown/highlighter.js:60:83)
    at file:///../sveltepress-project/node_modules/.pnpm/@sveltepress+theme-default@1.22.4_@algolia+client-search@4.22.1_@sveltejs+kit@2.5.0_@sveltejs_gzh4k2qsptoujdmnwzm3iacupy/node_modules/@sveltepress/theme-default/dist/markdown/highlighter.js:126:107
    at step (file:///../sveltepress-project/node_modules/.pnpm/@sveltepress+theme-default@1.22.4_@algolia+client-search@4.22.1_@sveltejs+kit@2.5.0_@sveltejs_gzh4k2qsptoujdmnwzm3iacupy/node_modules/@sveltepress/theme-default/dist/markdown/highlighter.js:32:23) {
  plugin: '@sveltepress/vite',
  id: '/../sveltepress-project/src/routes/hello/+page.md',
  pluginCode: '---\ntitle: Hello world\n---\n\nHere is some code\n\n```svelte\n<p>Hi</p>\n```'
}

```

Confirmd this bug in a [fresh](https://github.com/gka/sveltepress-highlighter-theme-bug) sveltepress instance.

### Reproduction

https://github.com/gka/sveltepress-highlighter-theme-bug

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by gka** [comment]
sorry, wrong repo
