### ISSUE TITLE
Monaco Editor: Normalize Hex code

### ISSUE THREAD

**Issue by hiddenest** [shikijs/shiki#594]
### Describe the bug
Monaco editor returns an error while using `github-light` theme by `@shikijs/monaco`.

```
Uncaught Error: Illegal value for token color: #fff

Error: Illegal value for token color: #fff
    at f.getId (tokenization.ts:173:10)
    at D (tokenization.ts:141:37)
    at _.createFromParsedTokenTheme (tokenization.ts:199:10)
    at _.createFromRawTokenTheme (tokenization.ts:195:15)
    at get tokenTheme (standaloneThemeService.ts:152:34)
    at p._toBinaryTokens (standaloneLanguages.ts:202:64)
    at p.tokenizeEncoded (standaloneLanguages.ts:241:23)
    at r (textModelTokens.ts:398:28)
    at t.updateTokensUntilLine (textModelTokens.ts:69:14)
    at c._tokenizeOneInvalidLine (textModelTokens.ts:510:33)
    at c._backgroundTokenizeForAtLeast1ms (textModelTokens.ts:487:37)
    at Object.p [as callback] (textModelTokens.ts:457:9)
    at platform.ts:191:17
    at wrapped (build.umd.js:690:53)
    at errors.ts:26:12
    at wrapped (build.umd.js:690:53)
```

### Reproduction
Use `github-light` or `github-dark` theme by [Monaco editor integrations](https://shiki.matsu.io/packages/monaco)

### Suggested Solution
Format 3, 4 letter shortcut hexcodes into valid format:
- 6 letter (RGB)
- 8 letter (RGB + transparent)

### Validations
- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hiddenest** [comment]
@antfu Hi! Thanks for your quick update. However, in the new version, color set converted into wrong hexcode.
e. g. `#fff` become `#ff0000` (You can reproduce this problem in the same `github-light` theme)

<img width="342" alt="스크린샷 2024-02-19 오전 12 21 38" src="https://github.com/shikijs/shiki/assets/8682478/e45b8b58-36bb-44be-a8e7-fa0035a99014">
