### ISSUE TITLE
ansi highlighting not working with theme dark-plus

### ISSUE THREAD

**Issue by chwzr** [shikijs/shiki#597]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

When using theme `dark-plus` and  language `ansi` together shiki fails to render anything with following error:

```ansi
index.js:27 TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at applyColorReplacements (index.mjs:125:33)
    at eval (index.mjs:460:17)
    at Array.map (<anonymous>)
    at eval (index.mjs:449:52)
    at Array.map (<anonymous>)
    at tokenizeAnsiWithTheme (index.mjs:449:18)
    at _codeToTokensBase (index.mjs:518:16)
    at _codeToTokens (index.mjs:771:18)
    at _codeToHast (index.mjs:1003:53)
    at _codeToHtml (index.mjs:4564:25)
    at Object.codeToHtml (index.mjs:5357:40)
    at _callee9$ (index.mjs:5441:26)
    at tryCatch (regeneratorRuntime.js:45:16)
    at Generator.eval (regeneratorRuntime.js:133:17)
    at Generator.eval [as next] (regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (asyncToGenerator.js:3:24)
    at _next (asyncToGenerator.js:22:9)
```

Other themes are working fine (e.g. monokai). Included a simple Reproduction Code Sandbox.

### Reproduction

https://codesandbox.io/p/sandbox/dark-plus-ansi-8qkpwj?file=%2Fsrc%2Findex.ts%3A1%2C1-20%2C1

### Contributes

- [x] I am willing to submit a PR to fix this issue
- [x] I am willing to submit a PR with failing tests

**Comment by chwzr** [comment]
Figured out that adding optional chaining operator to `color.toLowerCase()` will make highlighting work.

https://github.com/shikijs/shiki/blob/b6d40a3d6e4627eb983bc68e69eba9cc15821d51/packages/core/src/utils.ts#L149-L151

is this solution acceptable?

```ts
export function applyColorReplacements(color: string, replacements?: Record<string, string>): string {
  return replacements?.[color?.toLowerCase()] || color
}
```

**Comment by chwzr** [comment]
I've implemented a PR for this. Please let me know if this fix is acceptable or if you think there is another way to fix it.
