### ISSUE TITLE
@shikijs/monaco several themes that TypeError

### ISSUE THREAD

**Issue by taiyuuki** [shikijs/shiki#668]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

The monaco-editor version is 0.48.0,  @shikijs/monaco  v1.4.0

I tried all the themes from shiki, everything else is fine, but three themes that get errors

- github-dark-default
- github-dark-dimmed
- vesper

The errors reported by `github-dark-default` and `github-dark-dimmed`

```shell
Uncaught (in promise) TypeError: color.charCodeAt is not a function
    at normalizeColor (index.mjs:117:18)
    at index.mjs:21:72
    at Array.map (<anonymous>)
    at textmateThemeToMonacoTheme (index.mjs:21:40)
    at shikiToMonaco (index.mjs:35:25)
```

I found that this issue is cause that the resulting `symbolIcon.constantForeground
` field is an array,  normally it should be a string.

And then the error reported by `vesper`  is

```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'foreground')
    at textmateThemeToMonacoTheme (index.mjs:11:22)
    at shikiToMonaco (index.mjs:35:25)
```

This issue is cause that in `tokenColors`,  the `settings` field is missing for a item with the `scope: ['markup.quote']` .

I'm not sure if these are issues with the themes offered by `shiki`, or if they are issues with `shikiToMonaco`, or just with the monaco-editor version. Can anyone please check?

### Reproduction

https://github.com/taiyuuki/shiki-issue-typeerror

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by AmeroHan** [comment]
Errors occurred when using GitHub themes are caused by primer/github-vscode-theme#391, and Error occurred when using Vesper is because [there is a scope without `settings` field](https://github.com/shikijs/textmate-grammars-themes/blob/4130c1421523182fd917b2fcc16a485b05a7e0d6/packages/tm-themes/themes/vesper.json#L545). They mismatch `interface IRawThemeSetting`.

I don't know whether these theme JSONs ([packages/tm-themes](https://github.com/shikijs/textmate-grammars-themes/tree/4130c1421523182fd917b2fcc16a485b05a7e0d6/packages/tm-themes)) are managed by program or not, can I edit them and pull a request?

**Comment by MathiasWP** [comment]
A possible workaround until this has been fixed properly is to do the following:

const highlighter = await createHighlighter({
	themes: ['github-dark-default'],
	langs: languages
});

const githubDarkDefaultTheme = highlighter.getTheme('github-dark-default');
githubDarkDefaultTheme.colors!['symbolIcon.constantForeground'] = '#3fb950';
This will overwrite the invalid array with the correct string color, and then it works as expected.
