### ISSUE TITLE
Issue with the vuepress plugin

### ISSUE THREAD

**Issue by yzhang-gh** [shikijs/shiki#89]
Thanks for the nice work.

I'm trying to use it with vuepress. However, I keep getting this error

```
error vuepress-plugin-shiki apply ready failed.
RangeError: Invalid array length
    at __spreadArrays (D:\Workspace\notes\node_modules\shiki\dist\highlighter.js:40:18)
    at Object.<anonymous> (D:\Workspace\notes\node_modules\shiki\dist\highlighter.js:71:37)
    at step (D:\Workspace\notes\node_modules\shiki\dist\highlighter.js:33:23)
    at Object.next (D:\Workspace\notes\node_modules\shiki\dist\highlighter.js:14:53)
    at D:\Workspace\notes\node_modules\shiki\dist\highlighter.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Workspace\notes\node_modules\shiki\dist\highlighter.js:4:12)
    at Object.getHighlighter (D:\Workspace\notes\node_modules\shiki\dist\highlighter.js:55:12)
    at ready (D:\Workspace\notes\node_modules\vuepress-plugin-shiki\index.js:8:23)
    at AsyncOption.asyncApply (D:\Workspace\notes\node_modules\@vuepress\core\lib\node\plugin-api\abstract\AsyncOption.js:33:21)
```

no matter I use `npm` or `yarn`. My `config.js` file looks like below

```js
module.exports = {
    plugins: [
        '@vuepress/back-to-top',
        '@vuepress/medium-zoom',
        [
            'shiki', { theme: 'nord' }
        ],
    ],
}
```

Also tried the way showed [here](https://github.com/shikijs/shiki/blob/master/packages/vuepress-plugin/README.md) but no luck.

**Comment by octref** [comment]
Sorry about that, will work in 0.2.4.

**Comment by yzhang-gh** [comment]
Many thanks!
